config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :vendors
  # get 'vendor/index'
  get 'vendor/contact'
  root 'vendor#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/vendor.rb
class Vendor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/vendor_controller.rb
class VendorController < ApplicationController
  def index

  end
  def contact
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: %i[ show edit update destroy ]

  # GET /vendors or /vendors.json
  def index
    @vendors = Vendor.all
  end

  # GET /vendors/1 or /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors or /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendor_url(@vendor), notice: "Vendor was successfully created." }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1 or /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendor_url(@vendor), notice: "Vendor was successfully updated." }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1 or /vendors/1.json
  def destroy
    @vendor.destroy

    respond_to do |format|
      format.html { redirect_to vendors_url, notice: "Vendor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def vendor_params
      params.require(:vendor).permit(:name, :email, :mobile, :date, :note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vendor_helper.rb
module VendorHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
 <%= notice  %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Vendors</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'vendor/header' %>
    <br/>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br/>
      <%= yield %>
    </div>
    <%= render 'vendor/footer' %>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/vendors/_form.html.erb
<%= form_with(model: vendor) do |form| %>
  <% if vendor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
        <% vendor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :mobile, style: "display: block" %>
    <%= form.text_field :mobile , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :date, style: "display: block" %>
    <%= form.datetime_field :date , class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :note, style: "display: block" %>
    <%= form.text_area :note , class:"form-control" %>
  </div>
  <br/>
  <div class="field form-group">
    <%= form.submit class:'btn btn-secondary' %>
  </div>
<% end %>

app/views/vendors/_vendor.html.erb
<div id="<%= dom_id vendor %>">
  <p>
    <strong>Name:</strong>
    <%= vendor.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= vendor.email %>
  </p>

  <p>
    <strong>Mobile:</strong>
    <%= vendor.mobile %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= vendor.date %>
  </p>

  <p>
    <strong>Note:</strong>
    <%= vendor.note %>
  </p>

</div>

app/views/vendors/edit.html.erb
<h1>Editing vendor</h1>

<%= render "form", vendor: @vendor %>

<br>

<div>
  <%= link_to "Show this vendor", @vendor , class:'btn btn-secondary' %> |
  <%= link_to "Back to vendors", vendors_path , class:'btn btn-dark' %>
</div>

app/views/vendors/index.html.erb
<h1>All Vendors</h1>

<div id="vendors">
 

  <table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Mobile</th>
      <th scope="col">Date</th>
      <th scope="col">Information</th>
    </tr>
  </thead>
  <tbody>
    <% @vendors.each do |vendor| %>
    <tr>

      
      <td><%= vendor.name %></td>
      <td><%= vendor.email %></td>
      <td><%= vendor.mobile %></td>
      <td><%= vendor.date %></td>
      <td><%= vendor.note %></td>
      <td><%= link_to "Show", vendor , class:"btn btn-primary" %></td>
      
       
    </tr>


    <% end %>
  </tbody>
</table>
</div>

app/views/vendors/new.html.erb
<h1>New vendor</h1>

<%= render "form", vendor: @vendor %>

<br>

<div>
  <%= link_to "Back to vendors", vendors_path %>
</div>

app/views/vendors/show.html.erb
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= @vendor.name %></h5>
    
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= @vendor.email %></li>
    <li class="list-group-item"><%= @vendor.mobile %></li>
    <li class="list-group-item"><%= @vendor.date %></li>
    <li class="list-group-item"><%= @vendor.note %></li>
    
  </ul>
  <div  class="card-body">
      <%= link_to "Edit", edit_vendor_path(@vendor), class:"btn btn-primary" %>
      <%= link_to "Back", vendors_path , class:"btn btn-secondary" %><br/><br/>
      <%= button_to "Destroy", @vendor, method: :delete , class:"btn btn-danger"%>
        
  </div>
  
</div>